FROM ubuntu:24.04
LABEL description="Nervos CKB is a public permissionless blockchain, the common knowledge layer of Nervos network."
LABEL maintainer="Nervos Core Dev <dev@nervos.org>"

RUN groupadd -g 1001 ckb \
    && useradd -m -u 1001 -g ckb -s /bin/sh ckb \
    && mkdir -p /var/lib/ckb

WORKDIR /var/lib/ckb

COPY ./ckb ./docker/docker-entrypoint.sh /bin/
RUN chown -R ckb:ckb /var/lib/ckb \
    && chmod 755 /var/lib/ckb

USER ckb
ENV CKB_CHAIN=mainnet

EXPOSE 8114 8115
VOLUME ["/var/lib/ckb"]
ENTRYPOINT ["/bin/docker-entrypoint.sh"]
